image: node:12

pipelines:
  default:
    - step:
        name: Build and test
        script:
          - npm install
          - npm run build
          - npm run lint
          - npm test
  branches:
    "{master,develop}":
      - step:
          name: Build and test
          script:
            - npm install
            - npm run build
            - npm run lint
            - npm test
      - step:
          name: Deploy
          script:
            - git remote set-url origin ${BITBUCKET_GIT_SSH_ORIGIN}

            - printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" >> ~/.npmrc

            - if [ $BITBUCKET_BRANCH == 'master' ]; then
            - VERSION='patch'
            - else VERSION='prerelease'
            - fi
            - echo ${VERSION}

            - npm install
            - npm run build

            - npm version ${VERSION} --no-git-tag-version
            - npm publish

            - git add package.json package-lock.json
            - git commit -m "[skip ci] incremented version"
            - git push
